---

- name: Install Yara requirements from apt
  become: yes
  become_method: sudo
  package:
          name: "{{ yara_apt_requirements }}"
          state: latest

- name: install git
  become: yes
  become_method: sudo
  package:
          name: "git"
          state: latest
          
- name: Download yara with git
  become: yes
  become_method: sudo
  git:
          repo: https://github.com/VirusTotal/yara-python.git
          dest: "{{ yara_temp_dir }}"
          recursive: yes

- name: yara bootstrap
  become: yes
  become_method: sudo
  command: ./bootstrap.sh
  args:
          chdir: "{{ yara_temp_dir }}"/yara

- name: yara configure
  become: yes
  become_method: sudo
  command: ./configure
  args:
          chdir: "{{ yara_temp_dir }}"/yara

- name: yara Make install
  become: yes
  become_method: sudo
  command: make install
  args:
          chdir: "{{ yara_temp_dir }}"

- name: build yara python module
  become: yes
  become_method: sudo
  command: python setup.py build install
  args:
          chdir: "{{ yara_temp_dir }}"
