---

- name: Install Yara requirements from apt
  become: yes
  become_user: root
  package:
          name: "{{ yara_apt_requirements }}"
          state: latest

- name: install git
  become: yes
  become_user: root
  package:
          name: "git"
          state: latest
          
- name: Download yara with git
  become: yes
  become_user: root
  git:
          repo: https://github.com/VirusTotal/yara-python.git
          dest: "{{ yara_temp_dir }}"
          recursive: yes


- name: configure and build yara
  shell: |
    ./bootstrap.sh
    ./configure --prefix=/usr
    make && make install
  args:
    chdir: "{{ yara_temp_dir }}/yara"
  become: yes
  become_user: root

- name: build and install yara-python
  shell: |
    python setup.py build --dynamic-linking
    python setup.py install
  args:
    chdir: "{{ yara_temp_dir }}/yara"
  become: yes
  become_user: root

- name: symlink yara
  file:
    src: "{{ yara_lib }}"
    dest: "{{ yara_symlink_lib }}"
    owner: root
    group: root
    state: link
    mode: "u+rwx,g+rx,o+rx"
  become: yes
  become_user: root
