---

- name: Yara | Install package
  apt: name=yara state=latest
  become: yes
  become_user: root

- name: pip3 check if exists
  command: pip3 --version
  ignore_errors: yes
  register: pip3_present

- name: Install yara python module
  become: yes
  become_user: root
  pip:
    name: yara-python
    state: latest
    executable: pip3
    extra_args: "{{ pip_extra_args | default('') }}"
  when: pip3_present is success

- name: Yara | create folders
  file:
    path: "{{ yara_rules_path }}"
    state: directory
  become: yes
  become_user: root

- name: TMP Yara | add rules
  get_url:
    url: "{{ yara_rules_url }}"
    dest: "{{ yara_rules_path }}/yara_rules.yar"