---

- name: Yara | Install package
  apt: name=yara state=latest

- name: pip3 check if exists
  command: pip3 --version
  ignore_errors: yes
  register: pip3_present


  

- name: Install yara python module
  pip:
    name: yara-python
    state: latest
    executable: pip3
    extra_args: "{{ pip_extra_args | default('') }}"
  when: pip3_present is success
